let animatedMovies = {
  movies:[{
    no:1,
    name:"Song of the Sea",
    genre:["Animation, Adventure, Drama"],
    Stars: ["David Rawle, Brendan Gleeson, Lisa "],
    Director: "Tomm Moore",
    timing:"93 mins",
    year:2014,
    Votes: 68677,
   Gross: "$15.20M",
  },
{
  no:2,
    name:" Toy Story 3 ",
    genre:["Animation, Adventure, Comedy"],
    Stars: [" Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty"],
    Director: " Lee Unkrich ",
    timing:"103 mins",
    year:2010,
    Votes: 68633,
    Gross: "$17.20M",
},
{
  no:3,
  name:" Boy and the World ",
  genre:["Animation, Adventure, family"],
  Stars: ["Vinicius Garcia, Marco Aurélio Campos, Lu Horta, Felipe Zilse"],
  Director: " Alê Abreu ",
  timing:"80 mins",
  year:2013, 
  Votes: 53488,
  Gross: "$10.20M",
},
{
  no:4,
  name:"  In This Corner of the World  ",
  genre:["Animation, Adventure, family"],
  Stars: [" Non, Ava Pickard, Kenna Pickard, Karen Strassman"],
  Director: "Sunao Katabuchi ",
  timing:"129 mins",
  year:2016,
  Votes: 68288,
  Gross: "$18.20M",
},
{
  no:5,
  name:"  The Wind Rises ",
  genre:["Animation, Adventure, comedy"],
  Stars: [" Non, Ava Pickard, Kenna Pickard, Karen Strassman"],
  Director: "Peter Lord",
  timing:"88 mins",
  year:2012,
  Votes: 68338,
  Gross: "$12.20M",
},
{
  no:6,
  name:"   From Up on Poppy Hill  ",
  genre:["Animation, drama, family"],
  Stars: ["  Sarah Bolger, Chris Noth, Anton Yelchin, Christina Hendricks"],
  Director: " Gorô Miyazaki",
  timing:"91 mins",
  year:2011,
  Votes: 68778,
  Gross: "$13.20M",
},
{
  no:7,
  name:"  The Tale of The Princess Kaguya   ",
  genre:["Animation, Adventure, Drama"],
  Stars: ["  Chloë Grace Moretz, James Caan, Mary Steenburgen, James Marsden"],
  Director: " Gorô Miyazaki",
  timing:"137 min",
  year:2013,
  Votes: 22222,
  Gross: "$11.00M",
},
{
  no:8,
  name:"  The Secret World of Arrietty    ",
  genre:[" Animation, Adventure, Family"],
  Stars: [" Bridgit Mendler, Amy Poehler, Will Arnett, Moises Arias"],
  Director: " Hiromasa Yonebayashi",
  timing:"137 min",
  year:2013,
  Votes: 68688,
  Gross: "$19.20M",
},
{
  no:9,
  name:"  The red turtule   ",
  genre:[" Animation, fantasy"],
  Stars: ["  Jean-Hugues Anglade, Sebastien Dewaele, Benoit Dobbelstein,"],
  Director: " Jan Bultheel",
  timing:"80 min",
  year:2016,
  Votes: 210,
  Gross: "$1M",
},
{
  no:10,
  name:"  Cafard   ",
  genre:[" Animation, Drama"],
  Stars: ["  Jean-Hugues Anglade, Sebastien Dewaele, Benoit Dobbelstein, Dinara Drukarova"],
  Director: "  Michael Dudok de Wit",
  timing:"100 min",
  year:2015,
  Votes: 21110,
  Gross: "$1M",
},
{
  no:11,
  name:"   The Apostle  ",
  genre:[" Animation, horror"],
  Stars: ["  Jean-Hugues Anglade, Sebastien Dewaele, Benoit Dobbelstein"],
  Director: "  Fernando Cortizo",
  timing:"110 min",
  year:2014,
  Votes: 21110,
  Gross: "$1M",
},
{
  no:12,
  name:"   The Illusionist  ",
  genre:[" Animation, drama"],
  Stars: ["   Jean-Claude Donda, Eilidh Rankin, Duncan MacNeil, Raymond Mearns"],
  Director: " Sylvain Chome",
  timing:"110 min",
  year:2014,
  Votes: 31817,
  Gross: "$2.23M",
},
{
  no:13,
  name:"   Green Days  ",
  genre:[" Animation, drama, family"],
  Stars: ["Hye-yeong Jeon, Yeon-Seo Oh, Shin-Hye Park, Joo-Ae Seo"],
  Director: " Hye-jin Han",
  timing:"98 min",
  year:2019,
  Votes: 31817,
  Gross: "$4.23M",
},
{
  no:15,
  name:"Tito and the Birds ",
  genre:[" Animation, drama, action"],
  Stars: [" Pedro Henrique, Matheus Nachtergaele, Mateus Solano"],
  Director: "  Gabriel Bitar",
  timing:"98 min",
  year:2019,
  Votes: 31817,
  Gross: "$4.23M",
},
{
  no:15,
  name:"Night Is Short, Walk On Gir",
  genre:["Animation, Adventure, Comedy "],
  Stars: [" Gen Hoshino, Kana Hanazawa, Hiroshi Kamiya, Ryûji Akiyama"],
  Director: "Masaaki Yuasa  ",
  timing:" 92 min",
  year:2017,
  Votes: 2242  ,
  Gross: "$0.41M",
},
{
  no:17,
  name:" The Boy and the Beast",
  genre:[" Animation, Action, Adventure "],
  Stars: [" John Swasey, Randy E. Aguebor, Felecia Angelle, Bryn Apprill"],
  Director: "Mamoru Hosoda ",
  timing:"119 min ",
  year:2015,
  Votes: 16779  ,
  Gross: " $0.45M",
},
{
  no:18,
  name:" Ping Pong the Animation",
  genre:[" Animation, Drama, Sport"],
  Stars: [" Miyu Irino, Kana Hanazawa, Fumi Hirano, Gou Maeda"],
  Director: "  Makoto Shinkai",
  timing:"119 min ",
  year:2015,
  Votes:26100 ,
  Gross: "$0.45M",
},
{
  no:19,
  name:"The Garden of Words",
  genre:["Animation, Drama "],
  Stars: ["Kana Hanazawa, Fumi Hirano, Gou Maeda"],
  Director: "Makoto Shinka ",
  timing:"100 min",
  year:2010,
  Votes:45656 ,
  Gross: "$0.45M",
  Gross: " ",
},
{
  no:20,
  name:" Ronja, the Robber's Daughter",
  genre:["Animation "],
  Stars: [" Gillian Anderson, Teresa Gallagher, Rasmus Hardiker, Giles New"],
  Director: "Josiah Clark ",
  timing:"180 mins",
  year:2017,
  Votes:67090 ,
  Gross: "$0.45M",
  
},
{
  no:21,
  name:" Your Name",
  genre:["Animation, drama, fantasy "],
  Stars: [" Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Narita, Aoi Yûki"],
  Director: " Makoto Shinkai ",
  timing:"106 mins",
  year:2016,
  Votes:137415  ,
  Gross: "$5.02M",
},
{
  no:22,
  name:" The Little boy",
  genre:["Animation,drama "],
  Stars: ["Charlize Theron, Art Parkinson, Matthew McConaughey, Ralph Fiennes"],
  Director: "Travis Knight ",
  timing:"200 m ins",
  year:2019,
  Votes:7393 ,
  Gross: "$4.0M",
},
{
  no:23,
  name:" The Little Prince ",
  genre:["Animation, adventure, drama "],
  Stars: ["Charlize Theron, Art Parkinson, Matthew McConaughey, Ralph Fiennes"],
  Director: " Travis Knight ",
  timing:"108 mins",
  year:2016,
  Votes: 137415 ,
  Gross: " $5.02M",
},
{
  no:24,
  name:"Louise by the Shore",
  genre:["Animation "],
  Stars: ["Diane Dassigny, Piera Degli Esposti, Franciska Friede, "],
  Director: " Dominique Frot ",
  timing:"75 min ",
  year:2016,
  Votes: 626 ,
  Gross: "$5.02M",
},
{
  no:25,
  name:" Kubo and the Two Strings",
  genre:["Animation "],
  Stars: ["younshin ,yuki , min ah ,eon"],
  Director: "Travis Knight  ",
  timing:"102 mins",
  year: 2018,
  Votes:697979 ,
  Gross: "$4.01M",
},
{
  no:26,
  name:"Mary and the Witch's Flower",
  genre:["Animation, Adventure, Family"],
  Stars: ["Hana Sugisaki, Ryûnosuke Kamiki, Yûki Amami, Fumiyo Kohinata"],
  Director: "  Hiromasa Yonebayashi",
  timing:"103 mins",
  year:2017,
  Votes: 8826 ,
  Gross: "$2.42M",
},
{
  no:27,
  name:"Children Who Chase Lost Voices",
  genre:["Animation, Adventure, Drama "],
  Stars: [" Hilary Haag, Corey Hartzog, Leraldo Anzaldua, David Matranga"],
  Director: "  Leraldo Anzaldua",
  timing:"100 mins",
  year:2011,
  Votes:11719 ,
  Gross: "$6.02M",
},
{
  no:28,
  name:" The Girl Without Hands",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:29,
  name:"Lu over the Wall",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:30,
  name:" Loving Vincent",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:31,
  name:" The Adventures of Tintin",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:32,
  name:"Rango",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:33,
  name:" The Rabbi's Cat",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:34,
  name:" Another Day of Life",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:35,
  name:"Spider-Man: Into the Spider-Verse",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:36,
  name:" Mirai ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:37,
  name:" Isle of Dogs",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:38,
  name:" On Happiness Road",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:39,
  name:" Miss Hokusai ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:40,
  name:"Buñuel in the Labyrinth of the Turtles",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:41,
  name:"The Breadwinner",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:42,
  name:"",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:43,
  name:"Big Fish & Begonia",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:44,
  name:" A Silent Voice",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:45,
  name:" Have a Nice Day ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:46,
  name:" The Lego Movie ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:47,
  name:". A Letter to Momo ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:48,
  name:" Frankenweenie",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:49,
  name:"Over the Garden Wall",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:50,
  name:"Tangled",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:51,
  name:" The Fake ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:52,
  name:"",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:53,
  name:"Blame! ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "",
},
{
  no:54,
  name:" Despicable Me ",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"",
  year:,
  Votes: ,
  Gross: "$5.,",
},
{
  no:55,
  name:" Arthur Christmas",
  genre:["Animation "],
  Stars: [""],
  Director: " ",
  timing:"3 hrs",
  year: 2019,
  Votes:76943 ,
  Gross: "$8.09M",
},
{
  no:56,
  name:"Rio 2096: A Story of Love and Fury",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"2 hrs",
  year:2016,
  Votes:77886 ,
  Gross: "$8.09M",
},
{
  no:57,
  name:"",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"100 mins",
  year:2015,
  Votes: 22445,
  Gross: "$6.02M",
},
{
  no:58,
  name:"Another Day of Life",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"190 mins",
  year:2007,
  Votes:3345 ,
  Gross: "$5.02M",
},
{
  no:59,
  name:" The Book of Life",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"140 mins",
  year:2012,
  Votes:8864 ,
  Gross: "$7.06M",
},
{
  no:60,
  name:" Wolf Children",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"100 mins",
  year:2014,
  Votes: 2299,
  Gross: "$4.02M",
},
{
  no:61,
  name:"Time of Eve",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"90 mins",
  year:2010,
  Votes:6789 ,
  Gross: "$2.02M",
},
{
  no:62,
  name:" Wreck-It Ralph",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"150 mins",
  year:2011,
  Votes: 754436,
  Gross: "$1.02M",
},
{
  no:63,
  name:" A Cat in Paris",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"130 mins",
  year:2009,
  Votes: 87654,
  Gross: "$8.02M",
},
{
  no:64,
  name:"Frozen",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"200 mins",
  year:2011,
  Votes:34567 ,
  Gross: "$7.02M",
},
{
  no:65,
  name:" The Congress ",
  genre:[" "],
  Stars: [""],
  Director: " ",
  timing:"110 mins",
  year:2010,
  Votes:45678 ,
  Gross: "$5.02M",
},
  ]
}